Player
SoundManager Player.soundManager
Referenced by Start.
Shop Player.shop
Referenced by Start.
DataSavingManager Player.dataSavingManager
Referenced by Start.
PlayerData Player.playerData
Referenced by SavePlayerData, Start.
GameObject Player.pink_guy
Animator Player.anim
Referenced by Start.
Vector3 Player.clickPos
Referenced by MovePlayer, Start, StopMoving.
bool Player.moving
Referenced by MovePlayer, StopMoving, Update.
float Player.damageTimeRemaining
Referenced by Attacked, Update.
bool Player.damageTimerRunning
Referenced by Attacked, CanAttack, Update.
SpriteRenderer Player.sprite
Referenced by Start.
void Player.Start()
References anim, clickPos, dataSavingManager, playerData, shop, soundManager, sprite.
void Player.Awake()
void Player.Update()
References damageTimeRemaining, damageTimerRunning, MovePlayer, moving.
void Player.UpdateDamage()
Referenced by FlatDmgIncrease.
void Player.UpdateAttackSpeed()
Referenced by FlatAttackSpeedIncrease.
void Player.SavePlayerData()
References playerData.
Referenced by FlatAttackSpeedIncrease, FlatDmgIncrease, FlatMovementSpeedIncrease.
void Player.MovePlayer()
References clickPos, moving.
Referenced by Update.
float Player.GetDamage()
Provides the final damage value.
float Player.GetAttackSpeed()
Provides the final attack speed value.
Referenced by Attacked.
bool Player.CanAttack()
References damageTimerRunning.
Referenced by Block.FixedUpdate.
void Player.Attacked()
Called when the player has attacked, used to reset timer.
References damageTimeRemaining, damageTimerRunning, GetAttackSpeed.
void Player.FlatDmgIncrease(float damageIncrease)
Called by the Shop to increase the player by a flat amount when damage is upgraded.
damageIncrease
References SavePlayerData, UpdateDamage.
void Player.FlatAttackSpeedIncrease(float attkSpeedIncrease)
References SavePlayerData, UpdateAttackSpeed.
void Player.FlatMovementSpeedIncrease(float movementSpeedIncrease)
References SavePlayerData.
void Player.StopMoving()
References clickPos, moving.
void Player.KilledBlock(Block block)
This will handle the rewards for the player killing enemy.
block