DataSavingManager
string DataSavingManager.saveFileName
Referenced by Awake.
string DataSavingManager.saveFilePath
Referenced by Awake, Delete, InitializeGameData, Load, Save.
GameData DataSavingManager.gameData
Referenced by GetHelperData, GetOtherValue, GetSkill, Load, SeedGameData, SetHelperData, SetOtherValue, SetSkill.
int DataSavingManager.startingMoney
Referenced by SeedOtherValues.
void DataSavingManager.Awake()
References InitializeGameData, saveFileName, saveFilePath.
void DataSavingManager.Update()
void DataSavingManager.InitializeGameData()
References Load, saveFilePath, SeedGameData.
Referenced by Awake.
void DataSavingManager.Load()
References Delete, gameData, saveFilePath.
Referenced by InitializeGameData.
void DataSavingManager.SeedGameData()
References gameData, SeedBlockSpawnData, SeedOtherValues, SeedPlayerData, SeedSkills.
Referenced by InitializeGameData.
PlayerData DataSavingManager.SeedPlayerData()
Referenced by SeedGameData.
Dictionary<string, HelperData> DataSavingManager.SeedHelperData()
BlockSpawnData DataSavingManager.SeedBlockSpawnData()
Referenced by SeedGameData.
Dictionary<string, object> DataSavingManager.SeedOtherValues()
References startingMoney.
Referenced by SeedGameData.
Dictionary<string, Skill> DataSavingManager.SeedSkills()
References ATTKSPEED, DMG, KILLREWARD, MOVEMENTSPEED, SPAWNSPEED.
Referenced by SeedGameData.
void DataSavingManager.Save()
References saveFilePath.
void DataSavingManager.Delete()
Wipes out local values, and deletes configuration file (drastic, and should only be done if file is corrupted)
References saveFilePath.
Referenced by Load.
Skill DataSavingManager.GetSkill(string key)
References gameData, GameData.skillDictionary.
Dictionary<string, Skill> DataSavingManager.GetSkillDictionary()
void DataSavingManager.SetSkill(string key, Skill value)
References gameData, GameData.skillDictionary.
object DataSavingManager.GetOtherValue(string key)
References gameData, GameData.OtherValues.
Referenced by BlockSpawner.Start, Shop.Start.
void DataSavingManager.SetOtherValue(string key, object value)
References gameData, GameData.OtherValues.
PlayerData DataSavingManager.GetPlayerData()
void DataSavingManager.SetPlayerData(PlayerData playerData)
BlockSpawnData DataSavingManager.GetBlockSpawnData()
void DataSavingManager.SetBlockSpawnData(BlockSpawnData blockSpawnData)
HelperData DataSavingManager.GetHelperData(string key)
References gameData, GameData.HelperDictionary.
void DataSavingManager.SetHelperData(string key, HelperData value)
References gameData, GameData.HelperDictionary.