Shop
Dictionary<string, Skill> Shop.skillDictionary
This dictionary holds all skills with the skillName being the key.
Referenced by Start, UpgradeSkill.
DataSavingManager Shop.dataSavingManager
Referenced by Start.
UIManager Shop.uiManager
Referenced by Start.
BlockSpawner Shop.blockSpawner
Referenced by Start.
Player Shop.player
int Shop.playerMoney
The shop manages the player's money. This class is the only place the player's money should be altered.
Referenced by GetMoney, KilledBlock, UpdatePlayerMoneyAndUI, UpgradeSkill.
float Shop.playerMoneyMult
Referenced by ApplyPlayerUpgrade, KilledBlock, Start.
void Shop.Start()
References blockSpawner, dataSavingManager, DataSavingManager.GetOtherValue, playerMoneyMult, skillDictionary, uiManager, UpdatePlayerMoneyAndUI.
void Shop.Update()
void Shop.UpdatePlayerMoneyAndUI(int money)
NOTE THIS CURRENTLY SAVES EVERYTIME MONEY IS CHANGED FOR TESTING. This is the only place where the player's money is changed.
money
References playerMoney.
Referenced by KilledBlock, Start, UpgradeSkill.
void Shop.ApplyPlayerUpgrade(Skill upgradedSkill)
This method is called after skills are upgraded and changes the player to reflect the skill upgrades. It first switches on skill type and then calls player methods to handle changes.
upgradedSkill
References playerMoneyMult, Skill.type.
Referenced by UpgradeSkill.
void Shop.KilledBlock(int killReward)
This method is called by the player when a block is killed and handles the reward money for killing blocks.
killReward
References playerMoney, playerMoneyMult, UpdatePlayerMoneyAndUI.
int Shop.GetMoney()
Getter for the player's money.
References playerMoney.
Referenced by UIManager.SetDescriptionText.
bool Shop.UpgradeSkill(string skillName, out Skill upgradedSkill)
This method is called by the UIManager when an upgrade button is clicked. The skillName is provided and upgradedSkill is given alongside a bool as the return value. If the upgrade succeeds (enough money, not max level, etc), then the method returns true and upgradedSkill will be the skill that was changed.
skillName upgradedSkill
References ApplyPlayerUpgrade, playerMoney, skillDictionary, UpdatePlayerMoneyAndUI.
Referenced by UIManager.UpgradeSkill.