Helper
SoundManager Helper.soundManager
Referenced by Start.
DataSavingManager Helper.dataSavingManager
Referenced by Start.
HelperData Helper.helperData
Referenced by Start.
Vector3 Helper.targetPos
Referenced by FindBlockInRadius, MoveHelper, Start.
bool Helper.moving
Referenced by MoveHelper, StartCountdown.
float Helper.damageTimeRemaining
bool Helper.damageTimerRunning
SpriteRenderer Helper.sprite
float Helper.cdValue
Referenced by StartCountdown.
BlockSpawner Helper.blockSpawner
Referenced by FindBlockInRadius, Start.
float Helper.offset
Referenced by FindBlockInRadius.
void Helper.Start()
References blockSpawner, dataSavingManager, helperData, soundManager, StartCountdown, targetPos.
void Helper.Update()
References MoveHelper.
void Helper.MoveHelper()
References moving, targetPos.
Referenced by Update.
bool Helper.FindBlockInRadius()
References BlockSpawner.BlockDictionary, blockSpawner, offset, targetPos.
Referenced by StartCountdown.
IEnumerator Helper.StartCountdown(float countdownValue)
References cdValue, FindBlockInRadius, moving.
Referenced by Start.